name: CI

on:
  push:

  schedule:
    - cron: 0 0 * * 6

  workflow_dispatch:
    inputs:
      no-cache:
        description: Do not use cache when building the image.
        required:    false
        type:        boolean
        default:     false

jobs:
  cache:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        id:   script
        with:
          script: await require('.github/workflows/ci.js')({github, context, core, exec})
    outputs:
      no-cache: ${{ steps.script.outputs.no-cache }}
      tags:     ${{ steps.script.outputs.tags }}

  build:
    needs:    cache
    if:       needs.cache.outputs.no-cache == 'true' || github.event_name != 'schedule'
    runs-on:  ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to:   type=gha, mode=max
          no-cache:   ${{ needs.cache.outputs.no-cache }}
          pull:       ${{ needs.cache.outputs.no-cache }}
          tags:       ${{ needs.cache.outputs.tags }}
          push:       true
